#!/usr/bin/python

import sys, os, fnmatch

from mako.template import Template
from mako.lookup import TemplateLookup
from mako.runtime import Context

template_dir = 'templates/'
public_dir = 'public/'

lookup = TemplateLookup(directories=[template_dir], module_directory='/tmp/mako_modules')


def render(file):
    ofile = public_dir + file.replace('mako','html')
    buf = open(ofile,"w")
    ctx = Context(buf)
    lookup.get_template(file).render_context(ctx)
    buf.close()
    #TODO: calling system is not good. look up better ways
    os.system("git add " + ofile)

def main():
    for file in os.listdir(template_dir):
        if fnmatch.fnmatch(file, '*.mako'):
	    render(file)

if __name__ == "__main__":
    main()
